# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-03 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20170503_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
